import { Calendar, Gift, Heart, MessageSquare, Ticket, User } from "lucide-react";
import React from "react";

export const labelByType: Record<string, string> = {
  event_buy: "Покупка билета",
  event_activate: "Активация билета",
  event_save_toggle: "Сохранение события в избранное",
  quest_end: "Завершение квеста",

  case_buy: "Покупка кейса",
  case_open: "Открытие кейса",

  meet_create: "Создание встречи",
  meet_join_request: "Запрос на участие во встрече",
  meet_invites_send: "Отправка приглашения",
  meet_invite_send: "Отправка приглашения",
  meet_invite_unsend: "Отмена приглашения",
  meet_invite_decline: "Отклонение приглашения",
  meet_invite_accept: "Принятие приглашения",
  meet_leave: "Покидание встречи",
  meet_end: "Завершение встречи",
  share_meet: "Поделиться встречей",

  fast_meet_create: "Создание быстрой встречи",
  fast_meet_join: "Присоединение к быстрой встрече",
  fast_meet_leave: "Покидание быстрой встречи",
  fast_meet_accept: "Принятие заявки на быструю встречу",
  fast_meet_decline: "Отклонение заявки на быструю встречу",
  fast_meet_kick: "Исключение из быстрой встречи",
  fast_meet_delete: "Удаление быстрой встречи",

  onboarding_complete: "Завершение онбординга",
  profile_update: "Обновление профиля",
  favorite_add: "Добавление в избранное",
  favorite_remove: "Удаление из избранного",
  subscribe: "Подписка",
  unsubscribe: "Отписка",
  review_send: "Отправка отзыва",
  complaint_send: "Отправка жалобы",
  complaint_decline: "Отклонение жалобы",

  friend_request_send: "Заявка в друзья",
  friend_request_decline: "Отклонение заявки в друзья",
  friend_request_accept: "Принятие заявки в друзья",
  friend_request_cancel: "Отмена заявки в друзья",
  unfriend: "Удаление из друзей",
};

export const iconByType: Record<string, React.ReactNode> = {
  event_buy: <Ticket className="h-4 w-4" />,
  event_activate: <Ticket className="h-4 w-4" />,
  event_save_toggle: <Ticket className="h-4 w-4" />,
  quest_end: <Gift className="h-4 w-4" />,
  case_buy: <Gift className="h-4 w-4" />,
  case_open: <Gift className="h-4 w-4" />,
  meet_create: <Calendar className="h-4 w-4" />,
  meet_join_request: <Calendar className="h-4 w-4" />,
  meet_invites_send: <Calendar className="h-4 w-4" />,
  meet_invite_send: <Calendar className="h-4 w-4" />,
  meet_invite_unsend: <Calendar className="h-4 w-4" />,
  meet_invite_decline: <Calendar className="h-4 w-4" />,
  meet_invite_accept: <Calendar className="h-4 w-4" />,
  meet_leave: <Calendar className="h-4 w-4" />,
  meet_end: <Calendar className="h-4 w-4" />,
  fast_meet_create: <Calendar className="h-4 w-4" />,
  fast_meet_join: <Calendar className="h-4 w-4" />,
  fast_meet_leave: <Calendar className="h-4 w-4" />,
  fast_meet_accept: <Calendar className="h-4 w-4" />,
  fast_meet_decline: <Calendar className="h-4 w-4" />,
  fast_meet_kick: <Calendar className="h-4 w-4" />,
  fast_meet_delete: <Calendar className="h-4 w-4" />,
  onboarding_complete: <User className="h-4 w-4" />,
  profile_update: <User className="h-4 w-4" />,
  favorite_add: <Heart className="h-4 w-4" />,
  favorite_remove: <Heart className="h-4 w-4" />,
  subscribe: <User className="h-4 w-4" />,
  unsubscribe: <User className="h-4 w-4" />,
  review_send: <MessageSquare className="h-4 w-4" />,
  complaint_send: <MessageSquare className="h-4 w-4" />,
  complaint_decline: <MessageSquare className="h-4 w-4" />,
  friend_request_send: <User className="h-4 w-4" />,
  friend_request_decline: <User className="h-4 w-4" />,
  friend_request_accept: <User className="h-4 w-4" />,
  friend_request_cancel: <User className="h-4 w-4" />,
  unfriend: <User className="h-4 w-4" />,
};
