export const kinoData = [
  {
    id: 1,
    title: "Плагиатор",
    description: "Комедийная мелодрама о портале в прошлое, который меняет жизнь героя.",
    date: "13 июля",
    location: "Москва",
    price: 400,
    type: "Новинка",
    category: "Кино",
    stages: [{ title: "Сеанс", desc: "Просмотр фильма" }],
    reward: 0,
    quests: [],
    hasAchievement: false,
    organizer: "Яндекс Афиша",
    image:
      "https://avatars.mds.yandex.net/get-kinopoisk-image/10671298/9c2eb091-0db7-457c-98f6-c752ca390c3d/600x900",
  },
  {
    id: 2,
    title: "Не одна дома 2",
    description: "Семейная комедия о приключениях девочки, остающейся дома.",
    date: "13 июля",
    location: "Москва",
    price: 350,
    type: "Семейный",
    category: "Кино",
    stages: [{ title: "Сеанс", desc: "Просмотр фильма" }],
    quests: [],
    reward: 0,
    hasAchievement: false,
    organizer: "Яндекс Афиша",
    image:
      "https://avatars.mds.yandex.net/get-kinopoisk-image/10835644/f8fe7ec5-a907-48e1-9c16-901f4a9e002f/220x330",
  },
  {
    id: 3,
    title: "На деревню дедушке",
    description: "Российская комедия о деревенских приключениях.",
    date: "13 июля",
    location: "Москва",
    price: 300,
    type: "Комедия",
    quests: [],
    category: "Кино",
    stages: [{ title: "Сеанс", desc: "Просмотр фильма" }],
    reward: 0,
    hasAchievement: false,
    organizer: "Яндекс Афиша",
    image:
      "https://avatars.mds.yandex.net/get-kinopoisk-image/10900341/92a04bff-c3ff-4596-aa09-1dbdb130861b/600x900",
  },
  // {
  //   id: 4,
  //   title: "Хищные твари",
  //   description: "Фэнтези‑боевик с экшн-сценами и мистикой.",
  //   date: "13 июля",
  //   location: "Москва",
  //   price: 380,
  //   type: "Фэнтези",
  //   category: "Кино",
  //   stages: [{ title: "Сеанс", desc: "Просмотр фильма" }],
  //   reward: 0,
  //   hasAchievement: false,
  //   organizer: "Яндекс Афиша",
  //   images: ["https://avatars.mds.yandex.net/get-afisha/placeholder4"],
  // },
  // {
  //   id: 5,
  //   title: "Материалистка",
  //   description: "Мелодрама о людях и ценностях современной жизни.",
  //   date: "13 июля",
  //   location: "Москва",
  //   price: 320,
  //   type: "Драма",
  //   category: "Кино",
  //   stages: [{ title: "Сеанс", desc: "Просмотр фильма" }],
  //   reward: 0,
  //   hasAchievement: false,
  //   organizer: "Яндекс Афиша",
  //   images: ["https://avatars.mds.yandex.net/get-afisha/placeholder5"],
  // },
  // {
  //   id: 6,
  //   title: "Саван",
  //   description: "Драматическая история с эмоциональным посылом.",
  //   date: "13 июля",
  //   location: "Москва",
  //   price: 300,
  //   type: "Драма",
  //   category: "Кино",
  //   stages: [{ title: "Сеанс", desc: "Просмотр фильма" }],
  //   reward: 0,
  //   hasAchievement: false,
  //   organizer: "Яндекс Афиша",
  //   images: ["https://avatars.mds.yandex.net/get-afisha/placeholder6"],
  // },
  // {
  //   id: 7,
  //   title: "Побег из будущего",
  //   description: "Анимационная фантастика о путешествиях во времени.",
  //   date: "13 июля",
  //   location: "Москва",
  //   price: 350,
  //   type: "Фантастика",
  //   category: "Кино",
  //   stages: [{ title: "Сеанс", desc: "Просмотр фильма" }],
  //   reward: 0,
  //   hasAchievement: false,
  //   organizer: "Яндекс Афиша",
  //   images: ["https://avatars.mds.yandex.net/get-afisha/placeholder7"],
  // },
  // {
  //   id: 8,
  //   title: "Три богатыря. Ни дня без подвига 2",
  //   description: "Новая часть популярной анимационной франшизы.",
  //   date: "13 июля",
  //   location: "Москва",
  //   price: 280,
  //   type: "Анимация",
  //   category: "Кино",
  //   stages: [{ title: "Сеанс", desc: "Просмотр фильма" }],
  //   reward: 0,
  //   hasAchievement: false,
  //   organizer: "Яндекс Афиша",
  //   images: ["https://avatars.mds.yandex.net/get-afisha/placeholder8"],
  // },
  // {
  //   id: 9,
  //   title: "Балерина",
  //   description: "Триллер о жизни и опасностях балетного мира.",
  //   date: "13 июля",
  //   location: "Москва",
  //   price: 350,
  //   type: "Триллер",
  //   category: "Кино",
  //   stages: [{ title: "Сеанс", desc: "Просмотр фильма" }],
  //   reward: 0,
  //   hasAchievement: false,
  //   organizer: "Яндекс Афиша",
  //   image: "https://avatars.mds.yandex.net/get-afisha/placeholder9",
  // },
  // {
  //   id: 10,
  //   title: "Синистер. Семейное проклятие",
  //   description: "Ужастик о страшной семейной тайне.",
  //   date: "13 июля",
  //   location: "Москва",
  //   price: 330,
  //   type: "Ужасы",
  //   category: "Кино",
  //   stages: [{ title: "Сеанс", desc: "Просмотр фильма" }],
  //   reward: 0,
  //   hasAchievement: false,
  //   organizer: "Яндекс Афиша",
  //   image: "https://avatars.mds.yandex.net/get-afisha/placeholder10",
  // },
];
