/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SkillsImport } from './routes/skills'
import { Route as QuestsImport } from './routes/quests'
import { Route as ProfileImport } from './routes/profile'
import { Route as MeetingsImport } from './routes/meetings'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const SkillsRoute = SkillsImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRoute,
} as any)

const QuestsRoute = QuestsImport.update({
  id: '/quests',
  path: '/quests',
  getParentRoute: () => rootRoute,
} as any)

const ProfileRoute = ProfileImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRoute,
} as any)

const MeetingsRoute = MeetingsImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/meetings': {
      id: '/meetings'
      path: '/meetings'
      fullPath: '/meetings'
      preLoaderRoute: typeof MeetingsImport
      parentRoute: typeof rootRoute
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileImport
      parentRoute: typeof rootRoute
    }
    '/quests': {
      id: '/quests'
      path: '/quests'
      fullPath: '/quests'
      preLoaderRoute: typeof QuestsImport
      parentRoute: typeof rootRoute
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/meetings': typeof MeetingsRoute
  '/profile': typeof ProfileRoute
  '/quests': typeof QuestsRoute
  '/skills': typeof SkillsRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/meetings': typeof MeetingsRoute
  '/profile': typeof ProfileRoute
  '/quests': typeof QuestsRoute
  '/skills': typeof SkillsRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/meetings': typeof MeetingsRoute
  '/profile': typeof ProfileRoute
  '/quests': typeof QuestsRoute
  '/skills': typeof SkillsRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/meetings' | '/profile' | '/quests' | '/skills'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/meetings' | '/profile' | '/quests' | '/skills'
  id: '__root__' | '/' | '/meetings' | '/profile' | '/quests' | '/skills'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MeetingsRoute: typeof MeetingsRoute
  ProfileRoute: typeof ProfileRoute
  QuestsRoute: typeof QuestsRoute
  SkillsRoute: typeof SkillsRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MeetingsRoute: MeetingsRoute,
  ProfileRoute: ProfileRoute,
  QuestsRoute: QuestsRoute,
  SkillsRoute: SkillsRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/meetings",
        "/profile",
        "/quests",
        "/skills"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/meetings": {
      "filePath": "meetings.tsx"
    },
    "/profile": {
      "filePath": "profile.tsx"
    },
    "/quests": {
      "filePath": "quests.tsx"
    },
    "/skills": {
      "filePath": "skills.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
